### ISSUE TITLE
Currency not supported by merchant

### ISSUE THREAD

**Issue by blackBeltCoderr** [dotmarn/ionic3-paystack#1]
Good day,

Thank you for this awesome repo. I managed to clone and perform some tests using your test-key. However, when I change it to my key I get an error below:

"We could not start this transaction
Currency not supported by merchant"

I am based in South Africa, so I would like to pay in ZAR. This is the currency enabled on my profile.

Where to change so that it use zar instead of NGN currency?

Thank you

**Comment by dotmarn** [comment]
This is from paystack. Check paystack documentation to be sure of what to do so that you will be able to pay using that currency.

**Comment by blackBeltCoderr** [comment]
will do so. thank you.

**Comment by hawknad1** [comment]
Hello guys, has anyone found the solution to this problem? I'm currently stuck on this and I don't know what to do next.

**Comment by MarvelNwachukwu** [comment]
I'm currently looking for a solution to this. It has to do with activating the USD payments on your Paystack account. I'll update this when I have more concrete information

**Comment by hawknad1** [comment]
Alright sure, thanks.
